// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	"github.com/parxyws/cozybox/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizationRepository creates a new instance of MockOrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type MockOrganizationRepository struct {
	mock.Mock
}

type MockOrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepository) EXPECT() *MockOrganizationRepository_Expecter {
	return &MockOrganizationRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) GetByID(ctx context.Context, id string) (*domain.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrganizationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrganizationRepository_GetByID_Call {
	return &MockOrganizationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrganizationRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_GetByID_Call) Return(organization *domain.Organization, err error) *MockOrganizationRepository_GetByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Organization, error)) *MockOrganizationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Insert(ctx context.Context, org *domain.Organization) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Organization) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockOrganizationRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - org *domain.Organization
func (_e *MockOrganizationRepository_Expecter) Insert(ctx interface{}, org interface{}) *MockOrganizationRepository_Insert_Call {
	return &MockOrganizationRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, org)}
}

func (_c *MockOrganizationRepository_Insert_Call) Run(run func(ctx context.Context, org *domain.Organization)) *MockOrganizationRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Organization
		if args[1] != nil {
			arg1 = args[1].(*domain.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Insert_Call) Return(err error) *MockOrganizationRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, org *domain.Organization) error) *MockOrganizationRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Update(ctx context.Context, org *domain.Organization) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Organization) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrganizationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - org *domain.Organization
func (_e *MockOrganizationRepository_Expecter) Update(ctx interface{}, org interface{}) *MockOrganizationRepository_Update_Call {
	return &MockOrganizationRepository_Update_Call{Call: _e.mock.On("Update", ctx, org)}
}

func (_c *MockOrganizationRepository_Update_Call) Run(run func(ctx context.Context, org *domain.Organization)) *MockOrganizationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Organization
		if args[1] != nil {
			arg1 = args[1].(*domain.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Update_Call) Return(err error) *MockOrganizationRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Update_Call) RunAndReturn(run func(ctx context.Context, org *domain.Organization) error) *MockOrganizationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
