services:
  postgres-master:
    image: docker.io/bitnami/postgresql:latest
    container_name: cozybox_master_db
    ports:
      - "5500:5432"
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: postgres_slave
      POSTGRESQL_REPLICATION_PASSWORD: 1gX7FzM91ytNVwBj
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: s408RZ1ej76vl9ta
      POSTGRESQL_DATABASE: cozybox
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: "true"
    volumes:
      - cozybox_postgres_master_data:/bitnami/postgresql
    networks:
      - cozybox_network_db

  postgres-replica1:
    image: docker.io/bitnami/postgresql:latest
    container_name: cozybox_replica_db
    depends_on:
      - postgres-master
    ports:
      - "5501:5432"
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: postgres_slave
      POSTGRESQL_REPLICATION_PASSWORD: 1gX7FzM91ytNVwBj
      POSTGRESQL_MASTER_HOST: postgres-master
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_PASSWORD: 1gX7FzM91ytNVwBj
    volumes:
      - cozybox_postgres_replica1_data:/bitnami/postgresql
    networks:
      - cozybox_network_db

  redis:
    image: redis:8.4.0
    container_name: cozybox_redis
    restart: always
    command: redis-server --appendonly yes --requirepass cmjpqcqbc000104kzca2o86rw
    ports:
      - "6379:6379"
    volumes:
      - cozybox_redis_data:/data
    networks:
      - cozybox_network_db

  minio:
    image: quay.io/minio/aistor/minio
    container_name: cozybox_minio
    restart: unless-stopped
    ports:
      - "9000:9000" # S3 API Port
      - "9090:9090" # Web Console Port
    environment:
      MINIO_ROOT_USER: cozyadmin
      MINIO_ROOT_PASSWORD: 215V1CK6v9V90mjC
      MINIO_LICENSE: "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MCwiaWF0IjoxLjc3ODY1ODc2MDY2OTI5MTQ3MmU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiOGFkN2ZiYjEtYTJlMy00Y2FlLWJkNjQtMDdkODBmMjUwMTNmIiwib3JnIjoiIiwicGxhbiI6IkZSRUUiLCJzdWIiOiJwYXJ4eXN1d29AZ21haWwuY29tIiwidHJpYWwiOmZhbHNlfQ.drBI6rTAwu1rUq9na9U2a3Yy0s9YjIR86fUX3ZQ9h3vvVv0b-6kF-ExbCVsOp3caeYzxOf9ql8ah23nRJPliIJIJeX4iU5BlIxQjz4865yqH5G9EyRog7nsfN8lusLLG"
    volumes:
      - cozybox_minio_data:/data
    command: server /data --console-address ":9090"

networks:
  cozybox_network_db:
    driver: bridge

volumes:
  cozybox_minio_data:
    driver: local
  cozybox_postgres_master_data:
  cozybox_postgres_replica1_data:
  cozybox_redis_data: