template: testify
packages:
  github.com/parxyws/cozybox/internal/app/auth:
    config:
      dir: internal/app/auth/mocks
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      UserRepository:
      TenantRepository:
      TenantMemberRepository:
      OrganizationRepository:
      SessionStore:
      Mailer:
      FileStorage:
      AuthService:
      TransactionManager:
      RepoFactory:
  github.com/parxyws/cozybox/internal/app/user:
    config:
      dir: internal/app/user/mocks
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      UserRepository:
  github.com/parxyws/cozybox/internal/app/contact:
    config:
      dir: internal/app/contact/mocks
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      ContactRepository:
      Service:
  github.com/parxyws/cozybox/internal/app/tenant:
    config:
      dir: internal/app/tenant/mocks
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      OrganizationRepository:
