// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) WithTransaction(ctx context.Context, fn func(tx *gorm.DB) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx *gorm.DB) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockTransactionManager_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx *gorm.DB) error
func (_e *MockTransactionManager_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockTransactionManager_WithTransaction_Call {
	return &MockTransactionManager_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockTransactionManager_WithTransaction_Call) Run(run func(ctx context.Context, fn func(tx *gorm.DB) error)) *MockTransactionManager_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx *gorm.DB) error
		if args[1] != nil {
			arg1 = args[1].(func(tx *gorm.DB) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionManager_WithTransaction_Call) Return(err error) *MockTransactionManager_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx *gorm.DB) error) error) *MockTransactionManager_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
