// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/parxyws/cozybox/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// PutObject provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) PutObject(ctx context.Context, input domain.UploadInput) (string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UploadInput) (string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UploadInput) string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UploadInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockFileStorage_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.UploadInput
func (_e *MockFileStorage_Expecter) PutObject(ctx interface{}, input interface{}) *MockFileStorage_PutObject_Call {
	return &MockFileStorage_PutObject_Call{Call: _e.mock.On("PutObject", ctx, input)}
}

func (_c *MockFileStorage_PutObject_Call) Run(run func(ctx context.Context, input domain.UploadInput)) *MockFileStorage_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UploadInput
		if args[1] != nil {
			arg1 = args[1].(domain.UploadInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_PutObject_Call) Return(key string, err error) *MockFileStorage_PutObject_Call {
	_c.Call.Return(key, err)
	return _c
}

func (_c *MockFileStorage_PutObject_Call) RunAndReturn(run func(ctx context.Context, input domain.UploadInput) (string, error)) *MockFileStorage_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
