// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Delete(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockSessionStore_Expecter) Delete(ctx interface{}, keys ...interface{}) *MockSessionStore_Delete_Call {
	return &MockSessionStore_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockSessionStore_Delete_Call) Run(run func(ctx context.Context, keys ...string)) *MockSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSessionStore_Delete_Call) Return(err error) *MockSessionStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_Delete_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockSessionStore_Expecter) Get(ctx interface{}, key interface{}) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(s string, err error) *MockSessionStore_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Set(ctx context.Context, key string, value string, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSessionStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - expiration time.Duration
func (_e *MockSessionStore_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockSessionStore_Set_Call {
	return &MockSessionStore_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockSessionStore_Set_Call) Run(run func(ctx context.Context, key string, value string, expiration time.Duration)) *MockSessionStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionStore_Set_Call) Return(err error) *MockSessionStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string, expiration time.Duration) error) *MockSessionStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetMultiple provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) SetMultiple(ctx context.Context, pairs map[string]string, expiration time.Duration) error {
	ret := _mock.Called(ctx, pairs, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetMultiple")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, time.Duration) error); ok {
		r0 = returnFunc(ctx, pairs, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_SetMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMultiple'
type MockSessionStore_SetMultiple_Call struct {
	*mock.Call
}

// SetMultiple is a helper method to define mock.On call
//   - ctx context.Context
//   - pairs map[string]string
//   - expiration time.Duration
func (_e *MockSessionStore_Expecter) SetMultiple(ctx interface{}, pairs interface{}, expiration interface{}) *MockSessionStore_SetMultiple_Call {
	return &MockSessionStore_SetMultiple_Call{Call: _e.mock.On("SetMultiple", ctx, pairs, expiration)}
}

func (_c *MockSessionStore_SetMultiple_Call) Run(run func(ctx context.Context, pairs map[string]string, expiration time.Duration)) *MockSessionStore_SetMultiple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStore_SetMultiple_Call) Return(err error) *MockSessionStore_SetMultiple_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_SetMultiple_Call) RunAndReturn(run func(ctx context.Context, pairs map[string]string, expiration time.Duration) error) *MockSessionStore_SetMultiple_Call {
	_c.Call.Return(run)
	return _c
}
