// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/parxyws/cozybox/internal/app/auth"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockRepoFactory creates a new instance of MockRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoFactory {
	mock := &MockRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoFactory is an autogenerated mock type for the RepoFactory type
type MockRepoFactory struct {
	mock.Mock
}

type MockRepoFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoFactory) EXPECT() *MockRepoFactory_Expecter {
	return &MockRepoFactory_Expecter{mock: &_m.Mock}
}

// MemberRepo provides a mock function for the type MockRepoFactory
func (_mock *MockRepoFactory) MemberRepo(tx *gorm.DB) auth.TenantMemberRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for MemberRepo")
	}

	var r0 auth.TenantMemberRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) auth.TenantMemberRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.TenantMemberRepository)
		}
	}
	return r0
}

// MockRepoFactory_MemberRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberRepo'
type MockRepoFactory_MemberRepo_Call struct {
	*mock.Call
}

// MemberRepo is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockRepoFactory_Expecter) MemberRepo(tx interface{}) *MockRepoFactory_MemberRepo_Call {
	return &MockRepoFactory_MemberRepo_Call{Call: _e.mock.On("MemberRepo", tx)}
}

func (_c *MockRepoFactory_MemberRepo_Call) Run(run func(tx *gorm.DB)) *MockRepoFactory_MemberRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoFactory_MemberRepo_Call) Return(tenantMemberRepository auth.TenantMemberRepository) *MockRepoFactory_MemberRepo_Call {
	_c.Call.Return(tenantMemberRepository)
	return _c
}

func (_c *MockRepoFactory_MemberRepo_Call) RunAndReturn(run func(tx *gorm.DB) auth.TenantMemberRepository) *MockRepoFactory_MemberRepo_Call {
	_c.Call.Return(run)
	return _c
}

// OrgRepo provides a mock function for the type MockRepoFactory
func (_mock *MockRepoFactory) OrgRepo(tx *gorm.DB) auth.OrganizationRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for OrgRepo")
	}

	var r0 auth.OrganizationRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) auth.OrganizationRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.OrganizationRepository)
		}
	}
	return r0
}

// MockRepoFactory_OrgRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrgRepo'
type MockRepoFactory_OrgRepo_Call struct {
	*mock.Call
}

// OrgRepo is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockRepoFactory_Expecter) OrgRepo(tx interface{}) *MockRepoFactory_OrgRepo_Call {
	return &MockRepoFactory_OrgRepo_Call{Call: _e.mock.On("OrgRepo", tx)}
}

func (_c *MockRepoFactory_OrgRepo_Call) Run(run func(tx *gorm.DB)) *MockRepoFactory_OrgRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoFactory_OrgRepo_Call) Return(organizationRepository auth.OrganizationRepository) *MockRepoFactory_OrgRepo_Call {
	_c.Call.Return(organizationRepository)
	return _c
}

func (_c *MockRepoFactory_OrgRepo_Call) RunAndReturn(run func(tx *gorm.DB) auth.OrganizationRepository) *MockRepoFactory_OrgRepo_Call {
	_c.Call.Return(run)
	return _c
}

// TenantRepo provides a mock function for the type MockRepoFactory
func (_mock *MockRepoFactory) TenantRepo(tx *gorm.DB) auth.TenantRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for TenantRepo")
	}

	var r0 auth.TenantRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) auth.TenantRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.TenantRepository)
		}
	}
	return r0
}

// MockRepoFactory_TenantRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TenantRepo'
type MockRepoFactory_TenantRepo_Call struct {
	*mock.Call
}

// TenantRepo is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockRepoFactory_Expecter) TenantRepo(tx interface{}) *MockRepoFactory_TenantRepo_Call {
	return &MockRepoFactory_TenantRepo_Call{Call: _e.mock.On("TenantRepo", tx)}
}

func (_c *MockRepoFactory_TenantRepo_Call) Run(run func(tx *gorm.DB)) *MockRepoFactory_TenantRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoFactory_TenantRepo_Call) Return(tenantRepository auth.TenantRepository) *MockRepoFactory_TenantRepo_Call {
	_c.Call.Return(tenantRepository)
	return _c
}

func (_c *MockRepoFactory_TenantRepo_Call) RunAndReturn(run func(tx *gorm.DB) auth.TenantRepository) *MockRepoFactory_TenantRepo_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepo provides a mock function for the type MockRepoFactory
func (_mock *MockRepoFactory) UserRepo(tx *gorm.DB) auth.UserRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for UserRepo")
	}

	var r0 auth.UserRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) auth.UserRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.UserRepository)
		}
	}
	return r0
}

// MockRepoFactory_UserRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepo'
type MockRepoFactory_UserRepo_Call struct {
	*mock.Call
}

// UserRepo is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockRepoFactory_Expecter) UserRepo(tx interface{}) *MockRepoFactory_UserRepo_Call {
	return &MockRepoFactory_UserRepo_Call{Call: _e.mock.On("UserRepo", tx)}
}

func (_c *MockRepoFactory_UserRepo_Call) Run(run func(tx *gorm.DB)) *MockRepoFactory_UserRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoFactory_UserRepo_Call) Return(userRepository auth.UserRepository) *MockRepoFactory_UserRepo_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockRepoFactory_UserRepo_Call) RunAndReturn(run func(tx *gorm.DB) auth.UserRepository) *MockRepoFactory_UserRepo_Call {
	_c.Call.Return(run)
	return _c
}
