// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/parxyws/cozybox/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTenantRepository creates a new instance of MockTenantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantRepository {
	mock := &MockTenantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTenantRepository is an autogenerated mock type for the TenantRepository type
type MockTenantRepository struct {
	mock.Mock
}

type MockTenantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantRepository) EXPECT() *MockTenantRepository_Expecter {
	return &MockTenantRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockTenantRepository
func (_mock *MockTenantRepository) GetByID(ctx context.Context, id string) (*domain.Tenant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Tenant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Tenant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tenant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTenantRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTenantRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTenantRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTenantRepository_GetByID_Call {
	return &MockTenantRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTenantRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTenantRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantRepository_GetByID_Call) Return(tenant *domain.Tenant, err error) *MockTenantRepository_GetByID_Call {
	_c.Call.Return(tenant, err)
	return _c
}

func (_c *MockTenantRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Tenant, error)) *MockTenantRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function for the type MockTenantRepository
func (_mock *MockTenantRepository) GetBySlug(ctx context.Context, slug string) (*domain.Tenant, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *domain.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Tenant, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Tenant); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tenant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTenantRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockTenantRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockTenantRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockTenantRepository_GetBySlug_Call {
	return &MockTenantRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockTenantRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockTenantRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantRepository_GetBySlug_Call) Return(tenant *domain.Tenant, err error) *MockTenantRepository_GetBySlug_Call {
	_c.Call.Return(tenant, err)
	return _c
}

func (_c *MockTenantRepository_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Tenant, error)) *MockTenantRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockTenantRepository
func (_mock *MockTenantRepository) Insert(ctx context.Context, tenant *domain.Tenant) error {
	ret := _mock.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Tenant) error); ok {
		r0 = returnFunc(ctx, tenant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTenantRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTenantRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant *domain.Tenant
func (_e *MockTenantRepository_Expecter) Insert(ctx interface{}, tenant interface{}) *MockTenantRepository_Insert_Call {
	return &MockTenantRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, tenant)}
}

func (_c *MockTenantRepository_Insert_Call) Run(run func(ctx context.Context, tenant *domain.Tenant)) *MockTenantRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Tenant
		if args[1] != nil {
			arg1 = args[1].(*domain.Tenant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantRepository_Insert_Call) Return(err error) *MockTenantRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTenantRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, tenant *domain.Tenant) error) *MockTenantRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTenantRepository
func (_mock *MockTenantRepository) Update(ctx context.Context, tenant *domain.Tenant) error {
	ret := _mock.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Tenant) error); ok {
		r0 = returnFunc(ctx, tenant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTenantRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTenantRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant *domain.Tenant
func (_e *MockTenantRepository_Expecter) Update(ctx interface{}, tenant interface{}) *MockTenantRepository_Update_Call {
	return &MockTenantRepository_Update_Call{Call: _e.mock.On("Update", ctx, tenant)}
}

func (_c *MockTenantRepository_Update_Call) Run(run func(ctx context.Context, tenant *domain.Tenant)) *MockTenantRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Tenant
		if args[1] != nil {
			arg1 = args[1].(*domain.Tenant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantRepository_Update_Call) Return(err error) *MockTenantRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTenantRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tenant *domain.Tenant) error) *MockTenantRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
