// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/parxyws/cozybox/internal/pkg/mail"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendOTP provides a mock function for the type MockMailer
func (_mock *MockMailer) SendOTP(to string, data mail.OTPData) error {
	ret := _mock.Called(to, data)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, mail.OTPData) error); ok {
		r0 = returnFunc(to, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockMailer_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - to string
//   - data mail.OTPData
func (_e *MockMailer_Expecter) SendOTP(to interface{}, data interface{}) *MockMailer_SendOTP_Call {
	return &MockMailer_SendOTP_Call{Call: _e.mock.On("SendOTP", to, data)}
}

func (_c *MockMailer_SendOTP_Call) Run(run func(to string, data mail.OTPData)) *MockMailer_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 mail.OTPData
		if args[1] != nil {
			arg1 = args[1].(mail.OTPData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMailer_SendOTP_Call) Return(err error) *MockMailer_SendOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_SendOTP_Call) RunAndReturn(run func(to string, data mail.OTPData) error) *MockMailer_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SendResetPassword provides a mock function for the type MockMailer
func (_mock *MockMailer) SendResetPassword(to string, data mail.ResetPasswordData) error {
	ret := _mock.Called(to, data)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, mail.ResetPasswordData) error); ok {
		r0 = returnFunc(to, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_SendResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResetPassword'
type MockMailer_SendResetPassword_Call struct {
	*mock.Call
}

// SendResetPassword is a helper method to define mock.On call
//   - to string
//   - data mail.ResetPasswordData
func (_e *MockMailer_Expecter) SendResetPassword(to interface{}, data interface{}) *MockMailer_SendResetPassword_Call {
	return &MockMailer_SendResetPassword_Call{Call: _e.mock.On("SendResetPassword", to, data)}
}

func (_c *MockMailer_SendResetPassword_Call) Run(run func(to string, data mail.ResetPasswordData)) *MockMailer_SendResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 mail.ResetPasswordData
		if args[1] != nil {
			arg1 = args[1].(mail.ResetPasswordData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMailer_SendResetPassword_Call) Return(err error) *MockMailer_SendResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_SendResetPassword_Call) RunAndReturn(run func(to string, data mail.ResetPasswordData) error) *MockMailer_SendResetPassword_Call {
	_c.Call.Return(run)
	return _c
}
