// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/parxyws/cozybox/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTenantMemberRepository creates a new instance of MockTenantMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantMemberRepository {
	mock := &MockTenantMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTenantMemberRepository is an autogenerated mock type for the TenantMemberRepository type
type MockTenantMemberRepository struct {
	mock.Mock
}

type MockTenantMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantMemberRepository) EXPECT() *MockTenantMemberRepository_Expecter {
	return &MockTenantMemberRepository_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockTenantMemberRepository
func (_mock *MockTenantMemberRepository) GetByUserID(ctx context.Context, userID string) (*domain.TenantMember, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.TenantMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.TenantMember, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.TenantMember); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TenantMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTenantMemberRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockTenantMemberRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTenantMemberRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockTenantMemberRepository_GetByUserID_Call {
	return &MockTenantMemberRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockTenantMemberRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockTenantMemberRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantMemberRepository_GetByUserID_Call) Return(tenantMember *domain.TenantMember, err error) *MockTenantMemberRepository_GetByUserID_Call {
	_c.Call.Return(tenantMember, err)
	return _c
}

func (_c *MockTenantMemberRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.TenantMember, error)) *MockTenantMemberRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockTenantMemberRepository
func (_mock *MockTenantMemberRepository) Insert(ctx context.Context, member *domain.TenantMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TenantMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTenantMemberRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTenantMemberRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - member *domain.TenantMember
func (_e *MockTenantMemberRepository_Expecter) Insert(ctx interface{}, member interface{}) *MockTenantMemberRepository_Insert_Call {
	return &MockTenantMemberRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, member)}
}

func (_c *MockTenantMemberRepository_Insert_Call) Run(run func(ctx context.Context, member *domain.TenantMember)) *MockTenantMemberRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TenantMember
		if args[1] != nil {
			arg1 = args[1].(*domain.TenantMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTenantMemberRepository_Insert_Call) Return(err error) *MockTenantMemberRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTenantMemberRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, member *domain.TenantMember) error) *MockTenantMemberRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
