// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/parxyws/cozybox/internal/app/auth"
	"github.com/parxyws/cozybox/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// CompleteOnboarding provides a mock function for the type MockAuthService
func (_mock *MockAuthService) CompleteOnboarding(ctx context.Context, userID string, tenantID string, req *auth.OnboardingRequest, image *domain.UploadInput) error {
	ret := _mock.Called(ctx, userID, tenantID, req, image)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOnboarding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *auth.OnboardingRequest, *domain.UploadInput) error); ok {
		r0 = returnFunc(ctx, userID, tenantID, req, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_CompleteOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOnboarding'
type MockAuthService_CompleteOnboarding_Call struct {
	*mock.Call
}

// CompleteOnboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
//   - req *auth.OnboardingRequest
//   - image *domain.UploadInput
func (_e *MockAuthService_Expecter) CompleteOnboarding(ctx interface{}, userID interface{}, tenantID interface{}, req interface{}, image interface{}) *MockAuthService_CompleteOnboarding_Call {
	return &MockAuthService_CompleteOnboarding_Call{Call: _e.mock.On("CompleteOnboarding", ctx, userID, tenantID, req, image)}
}

func (_c *MockAuthService_CompleteOnboarding_Call) Run(run func(ctx context.Context, userID string, tenantID string, req *auth.OnboardingRequest, image *domain.UploadInput)) *MockAuthService_CompleteOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *auth.OnboardingRequest
		if args[3] != nil {
			arg3 = args[3].(*auth.OnboardingRequest)
		}
		var arg4 *domain.UploadInput
		if args[4] != nil {
			arg4 = args[4].(*domain.UploadInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthService_CompleteOnboarding_Call) Return(err error) *MockAuthService_CompleteOnboarding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_CompleteOnboarding_Call) RunAndReturn(run func(ctx context.Context, userID string, tenantID string, req *auth.OnboardingRequest, image *domain.UploadInput) error) *MockAuthService_CompleteOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// ForgotPassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ForgotPassword(ctx context.Context, req *auth.ForgotPasswordRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ForgotPasswordRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type MockAuthService_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.ForgotPasswordRequest
func (_e *MockAuthService_Expecter) ForgotPassword(ctx interface{}, req interface{}) *MockAuthService_ForgotPassword_Call {
	return &MockAuthService_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, req)}
}

func (_c *MockAuthService_ForgotPassword_Call) Run(run func(ctx context.Context, req *auth.ForgotPasswordRequest)) *MockAuthService_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ForgotPasswordRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.ForgotPasswordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_ForgotPassword_Call) Return(err error) *MockAuthService_ForgotPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, req *auth.ForgotPasswordRequest) error) *MockAuthService_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, req *auth.LoginRequest) (*auth.UserAuthenticateResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.UserAuthenticateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) (*auth.UserAuthenticateResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) *auth.UserAuthenticateResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserAuthenticateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.LoginRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.LoginRequest
func (_e *MockAuthService_Expecter) Login(ctx interface{}, req interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, req *auth.LoginRequest)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(userAuthenticateResponse *auth.UserAuthenticateResponse, err error) *MockAuthService_Login_Call {
	_c.Call.Return(userAuthenticateResponse, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, req *auth.LoginRequest) (*auth.UserAuthenticateResponse, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, sessionID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshToken(ctx context.Context, req *auth.RefreshTokenRequest) (*auth.UserAuthenticateResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *auth.UserAuthenticateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RefreshTokenRequest) (*auth.UserAuthenticateResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RefreshTokenRequest) *auth.UserAuthenticateResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserAuthenticateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.RefreshTokenRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.RefreshTokenRequest
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, req interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, req *auth.RefreshTokenRequest)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RefreshTokenRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.RefreshTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(userAuthenticateResponse *auth.UserAuthenticateResponse, err error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(userAuthenticateResponse, err)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, req *auth.RefreshTokenRequest) (*auth.UserAuthenticateResponse, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, req *auth.RegisterUserRequest) (*auth.RegisterResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.RegisterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RegisterUserRequest) (*auth.RegisterResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RegisterUserRequest) *auth.RegisterResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RegisterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.RegisterUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.RegisterUserRequest
func (_e *MockAuthService_Expecter) Register(ctx interface{}, req interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, req *auth.RegisterUserRequest)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RegisterUserRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.RegisterUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(registerResponse *auth.RegisterResponse, err error) *MockAuthService_Register_Call {
	_c.Call.Return(registerResponse, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, req *auth.RegisterUserRequest) (*auth.RegisterResponse, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ResetPassword(ctx context.Context, req *auth.ResetPasswordRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.ResetPasswordRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.ResetPasswordRequest
func (_e *MockAuthService_Expecter) ResetPassword(ctx interface{}, req interface{}) *MockAuthService_ResetPassword_Call {
	return &MockAuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, req)}
}

func (_c *MockAuthService_ResetPassword_Call) Run(run func(ctx context.Context, req *auth.ResetPasswordRequest)) *MockAuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.ResetPasswordRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.ResetPasswordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) Return(err error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, req *auth.ResetPasswordRequest) error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyEmail(ctx context.Context, req *auth.VerifyEmailRequest) (*auth.VerifyEmailResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 *auth.VerifyEmailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.VerifyEmailRequest) (*auth.VerifyEmailResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.VerifyEmailRequest) *auth.VerifyEmailResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerifyEmailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.VerifyEmailRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAuthService_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.VerifyEmailRequest
func (_e *MockAuthService_Expecter) VerifyEmail(ctx interface{}, req interface{}) *MockAuthService_VerifyEmail_Call {
	return &MockAuthService_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, req)}
}

func (_c *MockAuthService_VerifyEmail_Call) Run(run func(ctx context.Context, req *auth.VerifyEmailRequest)) *MockAuthService_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.VerifyEmailRequest
		if args[1] != nil {
			arg1 = args[1].(*auth.VerifyEmailRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyEmail_Call) Return(verifyEmailResponse *auth.VerifyEmailResponse, err error) *MockAuthService_VerifyEmail_Call {
	_c.Call.Return(verifyEmailResponse, err)
	return _c
}

func (_c *MockAuthService_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, req *auth.VerifyEmailRequest) (*auth.VerifyEmailResponse, error)) *MockAuthService_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
