// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package contact

import (
	"context"

	"github.com/parxyws/cozybox/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContactRepository creates a new instance of MockContactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContactRepository {
	mock := &MockContactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContactRepository is an autogenerated mock type for the ContactRepository type
type MockContactRepository struct {
	mock.Mock
}

type MockContactRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContactRepository) EXPECT() *MockContactRepository_Expecter {
	return &MockContactRepository_Expecter{mock: &_m.Mock}
}

// GetByIDAndTenant provides a mock function for the type MockContactRepository
func (_mock *MockContactRepository) GetByIDAndTenant(ctx context.Context, id string, tenantID string) (*domain.Contact, error) {
	ret := _mock.Called(ctx, id, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndTenant")
	}

	var r0 *domain.Contact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Contact, error)); ok {
		return returnFunc(ctx, id, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Contact); ok {
		r0 = returnFunc(ctx, id, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Contact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContactRepository_GetByIDAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndTenant'
type MockContactRepository_GetByIDAndTenant_Call struct {
	*mock.Call
}

// GetByIDAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tenantID string
func (_e *MockContactRepository_Expecter) GetByIDAndTenant(ctx interface{}, id interface{}, tenantID interface{}) *MockContactRepository_GetByIDAndTenant_Call {
	return &MockContactRepository_GetByIDAndTenant_Call{Call: _e.mock.On("GetByIDAndTenant", ctx, id, tenantID)}
}

func (_c *MockContactRepository_GetByIDAndTenant_Call) Run(run func(ctx context.Context, id string, tenantID string)) *MockContactRepository_GetByIDAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContactRepository_GetByIDAndTenant_Call) Return(contact *domain.Contact, err error) *MockContactRepository_GetByIDAndTenant_Call {
	_c.Call.Return(contact, err)
	return _c
}

func (_c *MockContactRepository_GetByIDAndTenant_Call) RunAndReturn(run func(ctx context.Context, id string, tenantID string) (*domain.Contact, error)) *MockContactRepository_GetByIDAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockContactRepository
func (_mock *MockContactRepository) Insert(ctx context.Context, contact *domain.Contact) error {
	ret := _mock.Called(ctx, contact)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Contact) error); ok {
		r0 = returnFunc(ctx, contact)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContactRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockContactRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - contact *domain.Contact
func (_e *MockContactRepository_Expecter) Insert(ctx interface{}, contact interface{}) *MockContactRepository_Insert_Call {
	return &MockContactRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, contact)}
}

func (_c *MockContactRepository_Insert_Call) Run(run func(ctx context.Context, contact *domain.Contact)) *MockContactRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Contact
		if args[1] != nil {
			arg1 = args[1].(*domain.Contact)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContactRepository_Insert_Call) Return(err error) *MockContactRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContactRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, contact *domain.Contact) error) *MockContactRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockContactRepository
func (_mock *MockContactRepository) List(ctx context.Context, tenantID string, search string, role string, page int, limit int) ([]domain.Contact, int64, error) {
	ret := _mock.Called(ctx, tenantID, search, role, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Contact
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]domain.Contact, int64, error)); ok {
		return returnFunc(ctx, tenantID, search, role, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []domain.Contact); ok {
		r0 = returnFunc(ctx, tenantID, search, role, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Contact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int64); ok {
		r1 = returnFunc(ctx, tenantID, search, role, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = returnFunc(ctx, tenantID, search, role, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockContactRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockContactRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - search string
//   - role string
//   - page int
//   - limit int
func (_e *MockContactRepository_Expecter) List(ctx interface{}, tenantID interface{}, search interface{}, role interface{}, page interface{}, limit interface{}) *MockContactRepository_List_Call {
	return &MockContactRepository_List_Call{Call: _e.mock.On("List", ctx, tenantID, search, role, page, limit)}
}

func (_c *MockContactRepository_List_Call) Run(run func(ctx context.Context, tenantID string, search string, role string, page int, limit int)) *MockContactRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockContactRepository_List_Call) Return(contacts []domain.Contact, n int64, err error) *MockContactRepository_List_Call {
	_c.Call.Return(contacts, n, err)
	return _c
}

func (_c *MockContactRepository_List_Call) RunAndReturn(run func(ctx context.Context, tenantID string, search string, role string, page int, limit int) ([]domain.Contact, int64, error)) *MockContactRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockContactRepository
func (_mock *MockContactRepository) SoftDelete(ctx context.Context, id string, tenantID string) error {
	ret := _mock.Called(ctx, id, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, tenantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContactRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockContactRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tenantID string
func (_e *MockContactRepository_Expecter) SoftDelete(ctx interface{}, id interface{}, tenantID interface{}) *MockContactRepository_SoftDelete_Call {
	return &MockContactRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, tenantID)}
}

func (_c *MockContactRepository_SoftDelete_Call) Run(run func(ctx context.Context, id string, tenantID string)) *MockContactRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContactRepository_SoftDelete_Call) Return(err error) *MockContactRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContactRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id string, tenantID string) error) *MockContactRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockContactRepository
func (_mock *MockContactRepository) Update(ctx context.Context, contact *domain.Contact) error {
	ret := _mock.Called(ctx, contact)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Contact) error); ok {
		r0 = returnFunc(ctx, contact)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContactRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContactRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - contact *domain.Contact
func (_e *MockContactRepository_Expecter) Update(ctx interface{}, contact interface{}) *MockContactRepository_Update_Call {
	return &MockContactRepository_Update_Call{Call: _e.mock.On("Update", ctx, contact)}
}

func (_c *MockContactRepository_Update_Call) Run(run func(ctx context.Context, contact *domain.Contact)) *MockContactRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Contact
		if args[1] != nil {
			arg1 = args[1].(*domain.Contact)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContactRepository_Update_Call) Return(err error) *MockContactRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContactRepository_Update_Call) RunAndReturn(run func(ctx context.Context, contact *domain.Contact) error) *MockContactRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
